### ISSUE TITLE
Can't read set map values between threads

### ISSUE THREAD

**Issue by asad-awadia** [barrust/hashmap#15]
I am running an OpenMP program with 2 threads. One thread sets some values and the other tries to read it but I don't get any set values back in the other thread

```
// thread 1 sets
int i = 0;
                for (i = 0; i < 10; i++)
                {
                    omp_set_lock(&writelock);
                    char key = i + '0';
                    printf("++setting key %d to val %d \n", key, i);
                    //#pragma omp critcal
                    hashmap_set_int(&h, &key, i);
                    omp_unset_lock(&writelock);
                }
```

```
               // thread 2 reading code
                sleep(5);
                int i = 0;
                for (i = 0; i < 10; i++)
                {
                    omp_set_lock(&writelock);
                    char key = i + '0';
                    int *hVal;
                    //#pragma omp critical
                    hVal = hashmap_get(&h, &key);
                    omp_unset_lock(&writelock);
                    if (hVal)
                    {
                        printf("hval is %d\n", *hVal);
                    }
                    else
                    {
                        printf("not found\n");
                    }
                }
```

`HashMap h;` is done at the top outside of main and `hashmap_init(&h);` is done in main

am I doing something wrong?

**Comment by barrust** [comment]
So I have attempted to pull your code into a script locally and I am getting compile errors. I assume it is a copy paste issue on one of our parts. Really, you should be checking if `hVal` is null to see if it passed or not. 

Something like this should work. Does the code work without openmp? Can you set and read the items in the hashmap in serial? 

```c 
hVal = hashmap_get(&h, &key);
if (hVal != null)
    printf("hval is %d\n", *hVal);
```

**Comment by asad-awadia** [comment]
` if (hVal)` is this not the same as `if (hVal != null)` ?

I haven't tried it without openmp - I am sure it works without it

https://github.com/rxi/map I tried using this map as well - and seem to be running into the same issue where the updated map values are not seen in the other thread

I am going to try with the updated if statement and report back

**Comment by barrust** [comment]
So, I did some digging into why your code as I reconstructed it did not work. It turns out that it seems to be a scoping issue of the `key` as they do not scope out beyond the different functions. I normally use the `\*alloc` family of functions when building my keys for my personal projects. 

I have uploaded a working version of the script here: [example_omp.txt](https://github.com/barrust/hashmap/files/4464626/example_omp.txt)

I hope this is helpful.

**Comment by barrust** [comment]
You can even make this change and it will still work so perhaps it is really an issue with just using a char as the key instead of a `c-string`.  
```c
/* comment out the alloc functions and use a char array */
char key[KEY_LEN] = {0};
sprintf(key, "%d", i);
// char* key = calloc(2, sizeof(char));
// key[0] = (char) i;
```

**Comment by asad-awadia** [comment]
Thank you for your help!

Will try today and let you know

**Comment by asad-awadia** [comment]
It works! Wow that would have taken me forever to find out Thanks!!

**Comment by barrust** [comment]
Glad to help!
